kind: pipeline
name: images
type: kubernetes

steps:
- name: build
  image: plugins/docker
  environment:
  settings:
    purge: false
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: zillownyc/drone-cli
    build_args:
    - DRONE_VERSION=1.2.1
    tags:
    - latest
    - "1.2.1"
    - "1.2"

trigger:
  event:
  - push
  branch:
  - master
